### PR TITLE
freeze dependencies

### PR DESCRIPTION
**Pull request by o-reo**
I propose to freeze the git dependencies to specific commits so we have a stable version.

### CODE REVIEW

**Comment by rubenrua** [comment]
Yes, I agree.

I would use a stable version and not a commit... ping @sdroege

**Comment by sdroege** [comment]
I'd recommend sticking to the 0.13 release of the gstreamer crates. That has everything you need, and you can then update again once 0.14 is released at some point. No need to follow git anymore.

**Comment by o-reo** [comment]
it should be better now, thanks.

**Comment by sdroege** [comment]
:+1:

**Comment by rubenrua** [comment]
Thank you @o-reo

**Pull request merged**
